# SPDX-FileCopyrightText: 2022 Forschungszentrum Jülich
#
# SPDX-License-Identifier: CC0-1.0

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install "poetry>=2.1.3,<3.0.0"
    post_install:
        # Install dependencies with 'docs' dependency group
        # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
        # VIRTUAL_ENV needs to be set manually for now, see #11150
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

# Build documentation in the docs/source directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true