# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileContributor: Michael Meinel
# SPDX-FileContributor: Michael Fritzsche
# SPDX-FileContributor: Stephan Druskat

import logging

from ruamel.yaml import YAML
import toml

from hermes.error import MisconfigurationError
from hermes.model.context_manager import HermesContext
from ..base import HermesCommand
from .base import HermesPostprocessPlugin


_log = logging.getLogger('postprocess.invenio')


class config_record_id(HermesPostprocessPlugin):
    def __call__(self, command: HermesCommand):
        ctx = HermesContext()
        ctx.prepare_step("deposit")
        with ctx["invenio"] as manager:
            deposition = manager["result"]
        ctx.finalize_step("deposit")

        conf = toml.load(open('hermes.toml', 'r'))
        try:
            old_record_id = conf["deposit"]["invenio"]["record_id"]
            if old_record_id == deposition["record_id"]:
                return
            _log.error("hermes.toml already contains a record_id for Invenio deposit.")
            raise MisconfigurationError(
                "Can't overwrite record_id automatically."
                f"(Tried to overwrite {old_record_id} with {deposition['record_id']})"
            )
        except KeyError:
            pass
        conf.setdefault("deposit", {}).setdefault("invenio", {})["record_id"] = deposition['record_id']
        toml.dump(conf, open('hermes.toml', 'w'))


class cff_doi(HermesPostprocessPlugin):
    def __call__(self, command: HermesCommand):
        ctx = HermesContext()
        ctx.prepare_step("deposit")
        with ctx["invenio"] as manager:
            deposition = manager["result"]
        ctx.finalize_step("deposit")

        yaml = YAML()
        yaml.default_flow_style = False
        yaml.allow_unicode = True
        yaml.indent(mapping=4, sequence=2, offset=0)
        yaml.allow_unicode = True

        try:
            cff = yaml.load(open('CITATION.cff', 'r'))
            new_identifier = {
                'description': f"DOI for the published version {deposition['metadata']['version']} "
                "[generated by hermes]",
                'type': 'doi',
                'value': deposition['doi']
            }
            if 'identifiers' in cff:
                cff['identifiers'].append(new_identifier)
            else:
                cff['identifiers'] = [new_identifier]
            yaml.dump(cff, open('CITATION.cff', 'w'))
        except Exception as e:
            raise RuntimeError("Update of CITATION.cff failed.") from e
