# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileContributor: Michael Meinel
# SPDX-FileContributor: Michael Fritzsche
# SPDX-FileContributor: Stephan Druskat

import json
import logging

from ruamel.yaml import YAML
import tomlkit

from hermes.error import MisconfigurationError

from ..base import HermesCommand
from .base import HermesPostprocessPlugin


_log = logging.getLogger('postprocess.invenio')


class config_record_id(HermesPostprocessPlugin):
    def __call__(self, command: HermesCommand):
        deposition = self.get_deposit_result("invenio")

        conf = self.load(tomlkit.load, open('hermes.toml', 'r'))
        try:
            old_record_id = conf["deposit"]["invenio"]["record_id"]
            if old_record_id == deposition["record_id"]:
                return
            _log.error("hermes.toml already contains a record_id for Invenio deposit.")
            raise MisconfigurationError(
                "Can't overwrite record_id automatically."
                f"(Tried to overwrite {old_record_id} with {deposition['record_id']})"
            )
        except KeyError:
            pass
        conf.setdefault("deposit", {}).setdefault("invenio", {})["record_id"] = deposition['record_id']
        self.write(tomlkit.dump, conf, open('hermes.toml', 'w'))


class cff_doi(HermesPostprocessPlugin):
    def __call__(self, command: HermesCommand):

        deposition = self.get_deposit_result("invenio")

        yaml = YAML()
        yaml.default_flow_style = False
        yaml.allow_unicode = True
        yaml.indent(mapping=4, sequence=2, offset=0)
        yaml.allow_unicode = True

        try:
            cff = self.load(yaml.load, open('CITATION.cff', 'r'))
            new_identifier = {
                'description': f"DOI for the published version {deposition['metadata']['version']} "
                "[generated by hermes]",
                'type': 'doi',
                'value': deposition['doi']
            }
            if 'identifiers' in cff:
                cff['identifiers'].append(new_identifier)
            else:
                cff['identifiers'] = [new_identifier]
            self.write(yaml.dump, cff, open('CITATION.cff', 'w'))
        except Exception as e:
            raise RuntimeError("Update of CITATION.cff failed.") from e


class codemeta_doi(HermesPostprocessPlugin):
    def __call__(self, command: HermesCommand):
        deposition = self.get_deposit_result("invenio")

        try:
            with open("codemeta.json", "r") as file:
                codemeta = self.load(json.load, file)
            if "@id" not in codemeta:
                codemeta["@id"] = deposition['doi']
            if "referencePublication" not in codemeta:
                codemeta["referencePublication"] = deposition['doi']
            elif isinstance(codemeta["referencePublication"], list):
                codemeta["referencePublication"].append(deposition['doi'])
            else:
                codemeta["referencePublication"] = [codemeta["referencePublication"], deposition['doi']]
            with open("codemeta.json", "w") as file:
                self.write(json.dump, codemeta, file)
        except Exception as e:
            raise RuntimeError("Update of CITATION.cff failed.") from e
