# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
#
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileContributor: Michael Fritzsche

import json
import sys

from ruamel import yaml
import toml

from hermes.commands import cli
from hermes.model import context_manager


def test_invenio_postprocess(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    input_file = tmp_path / ".hermes" / "deposit" / "invenio" / "result.json"
    input_file.parent.mkdir(parents=True, exist_ok=True)
    input_file.write_text("""{"record_id": "foo", "doi": "my_doi", "metadata": {"version": "1.0.0"}}""")

    citation_file = tmp_path / "CITATION.cff"
    citation_file.write_text("cff-version: 1.2.0\ntitle: Test")

    codemeta_file = tmp_path / "codemeta.json"
    codemeta_file.write_text(
        """{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "type": "SoftwareSourceCode",
    "name": "Test"
}
"""
    )

    config_file = tmp_path / "hermes.toml"
    config_file.write_text(
        """[postprocess]
run = ["config_invenio_record_id", "cff_doi", "codemeta_doi"]
[deposit.invenio]
site_url = "https://zenodo.org"
"""
    )

    orig_argv = sys.argv[:]
    sys.argv = ["hermes", "postprocess", "--path", str(tmp_path), "--config", str(config_file)]
    print(" ".join(sys.argv))
    result_cff = result_toml = {}
    try:
        monkeypatch.setattr(context_manager.HermesContext.__init__, "__defaults__", (tmp_path.cwd(),))
        cli.main()
    except SystemExit as e:
        if e.code != 0:
            raise e
    finally:
        result_toml = toml.load(config_file)
        result_cff = yaml.YAML().load(citation_file)
        result_codemeta = json.loads(codemeta_file.read_text())
        sys.argv = orig_argv

    assert result_toml == toml.loads(
        """[postprocess]
run = ["config_invenio_record_id", "cff_doi", "codemeta_doi"]
[deposit.invenio]
site_url = "https://zenodo.org"
record_id = "foo"
"""
    )
    assert result_cff == yaml.YAML().load(
        """cff-version: 1.2.0
title: Test
identifiers:
  - type: doi
    value: my_doi
    description: DOI for the published version 1.0.0 [generated by hermes]
"""
    )
    assert result_codemeta == json.loads(
        """{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "type": "SoftwareSourceCode",
    "@id": "my_doi",
    "name": "Test",
    "referencePublication": "my_doi"
}
"""
    )